# Generated by Django 4.2.24 on 2025-09-23 12:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baseline_dispersion",
                    models.FloatField(
                        default=0.1, help_text="Baseline gaze dispersion"
                    ),
                ),
                (
                    "baseline_blink_rate",
                    models.FloatField(
                        default=0.05, help_text="Baseline blink proxy rate"
                    ),
                ),
                (
                    "baseline_fixation_duration",
                    models.FloatField(
                        default=300.0, help_text="Baseline fixation duration in ms"
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "sample_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of samples used for baseline computation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attention_baseline",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lesson_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional lesson identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_info",
                    models.JSONField(
                        default=dict, help_text="Browser/device information"
                    ),
                ),
                (
                    "transport_used",
                    models.CharField(
                        choices=[("ws", "WebSocket"), ("rest", "REST API")],
                        default="ws",
                        help_text="Primary transport method used",
                        max_length=8,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attention_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ts_ms",
                    models.BigIntegerField(
                        help_text="Intervention timestamp in milliseconds"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("show_hint", "Show Hint"),
                            ("simplify", "Simplify Content"),
                            ("pause", "Pause Session"),
                            ("increase_difficulty", "Increase Difficulty"),
                            ("focus_nudge", "Focus Nudge"),
                            ("break_suggestion", "Break Suggestion"),
                        ],
                        help_text="Type of intervention",
                        max_length=24,
                    ),
                ),
                (
                    "reason",
                    models.JSONField(
                        default=dict,
                        help_text="Reasoning: event references, rationale, etc.",
                    ),
                ),
                (
                    "applied_by",
                    models.CharField(
                        choices=[("rule", "Rule Engine"), ("manual", "Manual")],
                        help_text="How the intervention was triggered",
                        max_length=8,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="attention.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "ts_ms"],
            },
        ),
        migrations.CreateModel(
            name="GazeSample",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ts_ms",
                    models.BigIntegerField(
                        help_text="Client timestamp in milliseconds since epoch"
                    ),
                ),
                (
                    "server_ts",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Server timestamp"
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        help_text="Normalized x coordinate [0,1]",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        help_text="Normalized y coordinate [0,1]",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Gaze tracking confidence [0,1]",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("question", "Question Area"),
                            ("options", "Answer Options"),
                            ("hint", "Hint Area"),
                            ("navigation", "Navigation"),
                            ("offscreen", "Off Screen"),
                            ("other", "Other"),
                        ],
                        help_text="UI zone where gaze was detected",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "dropped",
                    models.BooleanField(
                        default=False,
                        help_text="True if sample was filtered due to low confidence",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gaze_samples",
                        to="attention.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "ts_ms"],
            },
        ),
        migrations.CreateModel(
            name="FeatureWindow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "start_ms",
                    models.BigIntegerField(
                        help_text="Window start time in milliseconds"
                    ),
                ),
                (
                    "end_ms",
                    models.BigIntegerField(help_text="Window end time in milliseconds"),
                ),
                (
                    "features",
                    models.JSONField(
                        help_text="Computed features: fixations, dispersion, dwell times, etc."
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_windows",
                        to="attention.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "start_ms"],
            },
        ),
        migrations.CreateModel(
            name="AttentionEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ts_ms",
                    models.BigIntegerField(help_text="Event timestamp in milliseconds"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("on_task", "On Task"),
                            ("inattention", "Inattention"),
                            ("confusion", "Confusion"),
                            ("fatigue", "Fatigue"),
                        ],
                        help_text="Type of attention event",
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Confidence score [0,1]",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata: detector reasons, thresholds, etc.",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attention_events",
                        to="attention.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "ts_ms"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "-started_at"], name="attention_s_user_id_3d9588_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["session", "ts_ms"], name="attention_i_session_2da471_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gazesample",
            index=models.Index(
                fields=["session", "ts_ms"], name="attention_g_session_aa34ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gazesample",
            index=models.Index(
                fields=["session", "zone"], name="attention_g_session_97f18d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featurewindow",
            index=models.Index(
                fields=["session", "start_ms"], name="attention_f_session_0761c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featurewindow",
            unique_together={("session", "start_ms")},
        ),
        migrations.AddIndex(
            model_name="attentionevent",
            index=models.Index(
                fields=["session", "ts_ms"], name="attention_a_session_c4f17b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attentionevent",
            index=models.Index(
                fields=["session", "kind"], name="attention_a_session_0b86d0_idx"
            ),
        ),
    ]
